# Generated by Django 2.1.2 on 2018-11-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessor', '0002_photo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
