# Generated by Django 2.1.2 on 2018-11-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageprocessor', '0004_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
